### ISSUE TITLE
Phase retrieval

### ISSUE THREAD

**Issue by pretzsch** [ufo-kit/ufo-filters#190]
1. Please correct sign in tofu preprocess for qp:
        expression = '(isinf (v) || isnan (v)) ? 0.0f : -v'  -> should be +v

2. It would be good to have the following (both for TIE and qp):
    - Generally, the phase should be calculated.
    - If calculate_thickness = True and delta = ... is specified, the thickness should be calculated instead (and error message if delta is not specified)

3. Please correct prefactor for TIE retrieved phase.

**Comment by tfarago** [comment]
Regarding 2. point, I think it's over-complication because you can compute phase without delta by using any method, so the fact that you provide `delta` can serve as an indicator that you want to convert to thickness (will be documented this way) and you don't need the `calculate_thickness` flag on top of this.

**Comment by pretzsch** [comment]
Okay, seems reasonable!

**Comment by tfarago** [comment]
OK, let's move the discussion to the [correct issue tracker](https://github.com/ufo-kit/tofu/issues/94).
