### ISSUE TITLE
libhdf5-openmpi-1.8.4 crashes the hdf5 writer compilation

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#77]
On Ubuntu 12.04, the cmake recognizes it as a valid option, hence the HDF5 support is enabled but then the build fails.
```bash
[ 70%] Building C object src/CMakeFiles/ufofilterread.dir/readers/ufo-hdf5-reader.c.o
In file included from /usr/include/hdf5.h:24,
                 from /mnt/LSDF/anka-nc-cluster/all_users/sharedPrograms/ufo/git/ufo-filters/src/common/hdf5.h:11,
                 from /mnt/LSDF/anka-nc-cluster/all_users/sharedPrograms/ufo/git/ufo-filters/src/readers/ufo-hdf5-reader.c:20:
/usr/include/H5public.h:57: fatal error: mpi.h: No such file or directory
compilation terminated.
make[2]: *** [src/CMakeFiles/ufofilterread.dir/readers/ufo-hdf5-reader.c.o] Error 1
make[1]: *** [src/CMakeFiles/ufofilterread.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by matze** [comment]
I had a look and I will need to close this as WONTFIX. Here's the reasoning: There is no pkg-config support for HDF5 which is why we have to resort to CMake to find HDF5 and its flags. However, the CMake script does not report the include path to MPI hence this error. My suggestion is to set `WITH_HDF5` to `OFF` to disable HDF5 support. Defaulting to `OFF` is no solution in my opinion because then we will hurt all the other users with serial HDF5 who expect functioning HDF5 support if they have their dependencies installed.
